using UnityEngine;

public class PlatformReflection : MonoBehaviour
{
    private void OnCollisionEnter(Collision other)
    {
        if (other.gameObject.TryGetComponent(out Reflection小omponent reflection小omponent))
        {
            var hitPoint = other.contacts[0].point;
            float difference = transform.position.x - hitPoint.x;

            if (hitPoint.x < transform.position.x)
            {
                reflection小omponent.SetMovementDirection(new Vector2(Mathf.Abs(difference * 200), 100));
            }
            else
            {
                reflection小omponent.SetMovementDirection(new Vector2(-Mathf.Abs(difference * 200), 100));
            }
        }
    }
}